SAGERPNEW2018/Controllers/SectorInfoController.cs
using InventorySystemModel.InventoryModel;
using Newtonsoft.Json;
using SAGERPNEW2018.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAGERPNEW2018.Controllers
{
    public class SectorInfoController : Controller
    {
       
        [UserRightFilters]
        public ActionResult Index()
        {
            try
            {
                Gen_SectorInfo a = new Gen_SectorInfo();
                a.IsNew = Convert.ToBoolean(TempData["IsNew"]);
                a.Isedit = Convert.ToBoolean(TempData["IsEdit"]);
                a.Isdelete = Convert.ToBoolean(TempData["IsDelete"]);
                a.IsPrint = Convert.ToBoolean(TempData["IsPrint"]);
                return View(a);
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        [UserRightFilters]
        public ActionResult create(Gen_SectorInfo a)
        {
            try
            {
                a.IsNew = Convert.ToBoolean(TempData["IsNew"]);
                a.Isedit = Convert.ToBoolean(TempData["IsEdit"]);
                a.Isdelete = Convert.ToBoolean(TempData["IsDelete"]);
                a.IsPrint = Convert.ToBoolean(TempData["IsPrint"]);


                return View(a);
            }
            catch (Exception ex)
            {

                return View(a);
            }

        }
        [UserRightFilters]
        public ActionResult delete(int id)
        {
            try
            {
                Gen_SectorInfo a = new Gen_SectorInfo();

                bool c = a.DeleteData(id);
                if (c)
                {
                    return RedirectToAction("Index");

                }
                TempData["Dependancy"] = "This Record Using In Another Table";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }


        }
        [UserRightFilters]
        public ActionResult Edit(string id)
        {
            try
            {
                string[] ID = id.Split('|');

                Gen_SectorInfo a = new Gen_SectorInfo();
                var obj = a.getAlldataByID(Convert.ToInt32(ID[0]));
                if (ID[1] == "0")
                {
                    a.IsView = true;
                }
                return View("create", obj);

            }
            catch (Exception ex)
            {
                return View("create");
            }

        }
        public ActionResult Save(Gen_SectorInfo model)
        {
            try
            {
                int check;
                model.InActive = true;

                if (model.SectorID > 0)
                {
                    check = check = model.UpdateData(model);
                }
                else
                {

                    check = model.addata(model);
                }

                if (check > 0)
                {
                    return RedirectToAction("Index");

                }
                return RedirectToAction("create", model);

            }
            catch (Exception ex)
            {

                return View("create");
            }
        }
        public ActionResult Duplicate(string Name, Int32 ID)
        {
            try
            {
                string json = "";
                var list = new Gen_SectorInfo().checkDuplicate(ID, Name);
                if (list.Count() > 0)
                {
                    json = " Duplicate Record Found ";
                }
                return Json(JsonConvert.SerializeObject(json), JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {


                return Json(JsonConvert.SerializeObject("Error"), JsonRequestBehavior.AllowGet);

            }


        }
    }
}

SAGERPNEW2018/Views/SectorInfo/Index.cshtml
@model InventorySystemModel.InventoryModel.Gen_SectorInfo

@{
    ViewBag.Title = "Sector Information";
}


<div id="modals"></div>

<header class="page-header">
    <h2>@ViewBag.Title</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Setup</span></li>
            <li><span>@ViewBag.Title</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

<!-- start: page -->
<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">All @ViewBag.Title Data</h2>
    </header>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-6">
                <div class="mb-md">
                    @if (Model.IsNew)
                    {
                        <button type="button" id="Add" onclick="add()" class="btn btn-primary"> <i class="fa fa-plus"></i> Add New</button>
                        @* <button type="button" id="cancelll" onclick="window.history.back()" class="btn btn-primary">Cancel</button>*@
                    }

                </div>
            </div>
        </div>
        <table class="table table-bordered table-striped mb-none table-hover" id="UserTable">
            <thead>
                <tr>
                    <th>Code</th>
                    <th>Title </th>
                    <th>In Urdu </th>
                    <th>Description </th>
                    <th width="100px">Actions</th>
                </tr>
            </thead>

            <tbody id="ProductTableID">
                @foreach (var item in Model.GetAllSectorInfo())
                {
                    <tr>
                        <td> @item.Code </td>
                        <td> @item.SectorTitle </td>
                        <td> @item.SectorTitleInUrdu </td>
                        <td> @item.Description </td>

                        <td>
                            @if (Convert.ToBoolean(Model.Isedit))
                            {

                                <a href="#basicEdit" class="on-default edit-row mb-xs mt-xs mr-xs modal-with-zoom-anim" title="Edit" onclick="Edit(@item.SectorID)">
                                    <i class="fa fa-pencil"></i>

                                </a>
                            }
                            @if (Convert.ToBoolean(Model.Isdelete))
                            {
                                <a href="#basic" class="on-default edit-row mb-xs mt-xs mr-xs modal-with-zoom-anim" title="Delete" onclick="Del(@item.SectorID)">
                                    <i class="glyphicon glyphicon-trash"></i>

                                </a>
                            }
                            <a href="#" class="on-default edit-row" title="View" onclick="view(@item.SectorID)">
                                <i class="fa fa-table"></i>

                            </a>
                            @*<button class="btn btn-success btn-xs" onclick="view(@item["Voucherid"])"><span class="glyphicon glyphicon-blackboard"></span> View</button>*@
                        </td>

                    </tr>
                }
            </tbody>

        </table>
    </div>

</section>


<script>

    $(document).ready(function () {
        //$('#btnTriggerEdit').click();
        $("#modals").load('/CustomClasses/IndexModaling.html')


            $("#UserTable").dataTable(
               {
                   "aoColumns": [{ "bSearchable": true }, { "bSearchable": true }, { "bSearchable": true }, { "bSearchable": true },
                       { "bSearchable": false }],
                   "bSort": true,

                   dom: 'Bfrtip',
                   buttons: [
                              {
                                  extend: 'copy',
                                  text: '<span class="glyphicon glyphicon-floppy-disk"></span><span><strong> Copy</strong></span>',
                                  className: 'btn btn-primary  btn-sm',
                                  title: 'Sector Information',
                                  exportOptions: {
                                      columns: ':visible'
                                  }

                              },

                            {
                                extend: 'pdf',
                                text: '  <span class="glyphicon glyphicon-file"></span><span> PDF</strong></span>',
                                className: 'btn btn-primary  btn-sm',
                                title: 'Sector Information',
                                orientation: 'portrait',
                                pageSize: 'A4',
                                exportOptions: {
                                    columns: ':visible'
                                },

                                customize: function (doc) {

                                    doc.styles.title = {
                                        color: 'red',
                                        fontSize: '40',
                                        // background: 'blue',
                                        alignment: 'center'
                                    }
                                },



                            },

                             {

                                 title: 'Sector Information',
                                 text: '<span class="glyphicon glyphicon-th"></span><span><strong> Excel</strong></span>',
                                 className: 'btn btn-primary  btn-sm',
                                 orientation: 'portrait',
                                 pageSize: 'A4',
                                 extend: 'excel',
                                 footer: true,
                                 exportOptions: {
                                     columns: ':visible'
                                 }
                             },


                           {
                               extend: 'csv',

                               title: 'Sector Information',
                               text: '<span class="	glyphicon glyphicon-list-alt"></span><span><strong> CSV</strong></span>',
                               className: 'btn btn-primary  btn-sm',
                               exportOptions: {
                                   columns: ':visible'
                               }

                           },
                         {
                             extend: 'print',
                             title: 'Sector Information',
                             text: '<span class="glyphicon glyphicon-print"></span><span><strong> Print</strong></span>',
                             className: 'btn btn-primary  btn-sm',

                             exportOptions: { columns: ':visible' }

                         },
                         {

                             extend: 'colvis',
                             text: '<span class="glyphicon glyphicon-blackboard"></span><span><strong> Column visibility</strong></span>',
                             className: 'btn btn-primary  btn-sm',

                             //  'colvis'
                         }

                   ],
                   columnDefs: [{ targets: -1, visible: true }]
                   //paging: false
               })
            var a = '@TempData["Dependancy"]'
            if (a != "") {
                $("#basicDendent").modal('show');
            }
        })

        function add() {
            window.location.href = "/SectorInfo/create/"
        }

        var EditID = 0;
        var DeleteID = 0;
        function confirmPopupEdit()
        {
            window.location.href = "/SectorInfo/Edit/" + EditID + "|1"
        }

        function Edit(id) {
            EditID=id
        }

        function confirmPopupDelete() {
            window.location.href = "/SectorInfo/delete/" + DeleteID

        }
        function Del(id) {
            DeleteID = id
        }

        function view(id) {
            window.location.href = "/SectorInfo/Edit/" + id + "|0"

        }

</script>

SAGERPNEW2018/Views/SectorInfo/create.cshtml
@model InventorySystemModel.InventoryModel.Gen_SectorInfo


@{
    ViewBag.Title = "Sector Information";
}


@using (@Html.BeginForm("Save", "SectorInfo", FormMethod.Post, new { @id = "myform", enctype = "multipart/form-data" }))
{
    if (Model.SectorID > 0)
    {
        if (Model.IsView)
        {
            ViewBag.Title = "Sector Info View";
        }
        else
        {
            ViewBag.Title = "Sector Info Edit";
        }

    }
    else
    {

        ViewBag.Title = "Sector Info Create";

    }
    @Html.HiddenFor(m => m.SectorID)
    <header class="page-header">
        <h2>@ViewBag.Title</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="index.html">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Setup</span></li>
                <li><span>Sector Info</span></li>
            </ol>

            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>


    <div class="panel">
        <!-- start: page -->
        <div class="row">
            <div class="col-md-12">


                <section class="panel">
                    <header class="panel-heading">
                        <div class="panel-actions">
                            <a href="#" class="fa fa-caret-down"></a>
                            <a href="#" class="fa fa-times"></a>
                        </div>

                        <h2 class="panel-title">Sector Info</h2>
                        <p class="panel-subtitle">
                            Form control for input Sector Info data .
                        </p>
                    </header>
                    <div class="panel-body">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Sector <span class="required">*</span></label>
                            <div class="col-sm-9 ">
                                @Html.DropDownListFor(model => model.SectorID, Model.GetAllTown(), new { @placeholder = "Enter Type", @class = "form-control selectpicker " })

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Sector Code <span class="required">*</span></label>
                            <div class="col-sm-9 ">
                                @Html.TextBoxFor(model => model.Code, new { @class = "form-control uneditable-input ", required = "required", @placeholder = "Enter Code" })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">Title<span class="required">*</span></label>
                            <div class="col-sm-9 ">
                                @Html.TextBoxFor(model => model.SectorTitle, new { @class = "form-control uneditable-input ", required = "required", @placeholder = "Enter Title " })

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">In Urdu<span class="required">*</span></label>
                            <div class="col-sm-9 ">
                                @Html.TextBoxFor(model => model.SectorTitleInUrdu, new { @class = "form-control uneditable-input ", required = "required", @placeholder = "Enter In Urdu" })

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">Description<span class="required">*</span></label>
                            <div class="col-sm-9 ">
                                @Html.TextBoxFor(model => model.Description, new { @class = "form-control uneditable-input ", required = "required", @placeholder = "Enter Description" })

                            </div>
                        </div>
                    </div>
                    <footer class="panel-footer">
                        <div class="row">
                            <div class="col-sm-9">
                                <button type="button" onclick="postform()" class="btn btn-primary">Save</button>
                                <button type="button" id="cancelll" class="btn btn-default" onclick="window.history.back()">Cancel</button>
                            </div>
                        </div>
                    </footer>
                </section>

            </div>

        </div>

    </div>

}




<script src="/Content/assets/js/bootbox.min.js"></script>
<script>


    //function ShowImagePreview(imageUploader, previewImage) {
    //    if (imageUploader.files && imageUploader.files[0]) {
    //        var reader = new FileReader();
    //        reader.onload = function (e) {
    //            $(previewImage).attr('src', e.target.result);
    //        }
    //        reader.readAsDataURL(imageUploader.files[0]);
    //    }
    //}

    function postform() {

        var ReturnValue = true

        $("#myform").validate();




        var Data = { Name: $('#SectorTitle').val(), ID: $("#SectorID").val() }
        $.ajax({
            async: false,
            url: "/SectorInfo/Duplicate",
            data: Data,
            success: function (data) {

                var c =JSON.parse(data);
                if (c!="") {
                    bootbox.alert(c)
                    ReturnValue = false;
                }
            },
            error: function () {
                ReturnValue = false;
                bootbox.alert("Error")
            }
        })
        if (ReturnValue) {
            $("#myform").submit();

        }

    }
    $(document).ready(function () {
       // $('#Myform :input').select()

        $('.selectpicker').selectpicker('selectAll');

        if ('@Model.IsView' == 'True') {
            $('#myform :input').attr('disabled', true);
            $('#cancelll').attr('disabled', false);

        }

    });


</script>